---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  data_bags_path: './test/integration/data_bags'

verifier:
  name: inspec

platforms:
  # - name: ubuntu-16.04
  # - name: ubuntu-14.04
  # - name: centos-6.9
  - name: centos-7.4
  # - name: debian-7.11
  # - name: opensuse-leap-42

suites:
  - name: default
    run_list:
      - recipe[instana-agent::default]
    verifier:
      inspec_tests:
        - test/recipes/default
    attributes:
